### ISSUE TITLE
Build files?

### ISSUE THREAD

**Issue by mhvelplund** [toss-dev/Magic_Crusade_1_8#1]
This is quite possibly a noob question, but where are the build files to make the JAR?

**Comment by rpereira-dev** [comment]
Hey man, I dont work on this project no more

However, if you want to build it, you'll have to get a fresh new MCP (Minecraft coder pack, with MinecraftForge) and then, using gradle, generate a new Eclipse project

Only then you will be able to import sources into the Eclipse project and run it

Thats quite a mess but well, I was not used to this kind of project when I made it, sorry for complications :(
